slice_name: Turnover Day
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 5__table
  viz_type: table
  slice_id: 1387
  query_mode: aggregate
  groupby:
  - spin_date
  time_grain_sqla: P1D
  temporal_columns_lookup:
    spin_date: true
    client_registration_time: true
  metrics:
  - casino_uap
  - casino_spin_count
  - avg_spin_eur
  - casino_turnover_eur
  - casino_payout_eur
  - ggr_eur
  - ggr_percent
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: spin_date
  order_by_cols: []
  row_limit: 1000
  show_totals: true
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 925
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[{"col":"spin_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"spin_date","label":"spin_date","expressionType":"SQL"}],"metrics":["casino_uap","casino_spin_count","avg_spin_eur","casino_turnover_eur","casino_payout_eur","ggr_eur","ggr_percent"],"orderby":[["casino_uap",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]},{"filters":[{"col":"spin_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["casino_uap","casino_spin_count","avg_spin_eur","casino_turnover_eur","casino_payout_eur","ggr_eur","ggr_percent"],"annotation_layers":[],"row_limit":0,"row_offset":0,"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"spin_date"}],"all_columns":[],"allow_render_html":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","dashboards":[925],"datasource":"5__table","extra_form_data":{},"groupby":["spin_date"],"metrics":["casino_uap","casino_spin_count","avg_spin_eur","casino_turnover_eur","casino_payout_eur","ggr_eur","ggr_percent"],"order_by_cols":[],"percent_metrics":[],"query_mode":"aggregate","row_limit":1000,"show_cell_bars":true,"show_totals":true,"slice_id":2047,"table_timestamp_format":"smart_date","temporal_columns_lookup":{"client_registration_time":true,"spin_date":true},"time_grain_sqla":"P1D","viz_type":"table","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 88393360-6318-4d29-9bd1-5006377ee707
version: 1.0.0
dataset_uuid: bce7aad0-f8c8-4d09-9f5f-fe068cd3914b
